artifact_location: file:\\\C:\Users\indra\Desktop\MLOps_Udemy_Support_Docs\Entrega\15_End-to-end_MLOps_Project\ml_runs/421957848183978726
creation_time: 1769518732717
experiment_id: '421957848183978726'
last_update_time: 1769518732717
lifecycle_stage: active
name: employee-churn
